name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  check-docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Check markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.markdown-link-check.json'
        folder-path: 'docs/, .'
        file-extension: '.md'
    
    - name: Lint markdown files
      run: |
        npm install -g markdownlint-cli
        markdownlint '**/*.md' --ignore node_modules
    
    - name: Check spelling
      uses: streetsidesoftware/cspell-action@v5
      with:
        files: '**/*.md'
        config: '.cspell.json'

  generate-api-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install TypeDoc
      run: npm install -g typedoc
    
    - name: Generate TypeDoc documentation
      run: |
        typedoc src/index.ts \
          --out docs/api \
          --name "MCP Drupal God Mod API" \
          --readme none \
          --excludePrivate \
          --excludeProtected \
          --disableSources
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/api
        destination_dir: api